services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - bookstore-network
    volumes:
      - ./app:/app/app
      - ./static:/app/static

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - bookstore-network
    command: bash -c "ollama serve & sleep 5 && ollama pull mxbai-embed-large"

networks:
  bookstore-network:
    driver: bridge

volumes:
  ollama-data:
