version: "3.8"

services:
  fastapi_chatbot:
    image: dhlananh/bookstore-chatbot-app:latest
    container_name: bookstore_fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "hieutrollmc.tino.page"
      DB_USER: "satancra_bookstore"
      DB_PASSWORD: "sEVXUF7ZsCrdXY9Ehzr3"
      DB_NAME: "satancra_bookService"

      OLLAMA_API_BASE_URL: http://ollama_server:11434
      OLLAMA_MODEL_NAME: "nomic-embed-text"
      OLLAMA_MODEL_EMBEDDING_SIZE: "768"
    depends_on:
      - ollama_server
    networks:
      - chatbot_net

  ollama_server:
    image: ollama/ollama:latest
    container_name: bookstore_ollama_server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatbot_net

volumes:
  ollama_data:

networks:
  chatbot_net:
    driver: bridge
